
const KEY="built-v2-real";
let D=JSON.parse(localStorage.getItem(KEY)||"null")||{
 clients:[{id:1,name:"Emma",weight:82.4,goal:78,history:[84,83.3,82.4],programId:null,dietId:null}],
 programs:[],library:[],diets:[],
 meals:[
  {id:1,name:"Proteiinipuuro + banaani",cat:"Aamiainen",kcal:520,p:35,c:72,f:10,foods:"Kaura, rahka, banaani"},
  {id:2,name:"Kana-riisikulho",cat:"Lounas",kcal:610,p:48,c:72,f:12,foods:"Kana, riisi, kasvikset"},
  {id:3,name:"Jauheliha-peruna",cat:"Päivällinen",kcal:640,p:45,c:60,f:22,foods:"Jauheliha 5 %, peruna, kasvikset"},
  {id:4,name:"Ruisleipä + munat",cat:"Välipala",kcal:390,p:25,c:42,f:14,foods:"Ruisleipä, kananmunat, kalkkuna"}
 ]};
let S={page:"home",cid:D.clients[0].id,role:"coach"};
function macroSuggestion(c){let w=+c.weight||80,h=+c.height||177,age=+c.age||31,a={low:1.2,moderate:1.45,high:1.65,veryhigh:1.8}[c.activity||"moderate"]||1.45;let bmr=10*w+6.25*h-5*age+5;let kcal=Math.round(bmr*a);let adj=c.goal==="lose"?-300:c.goal==="gain"?300:0;kcal=Math.max(1400,kcal+adj);let p=Math.round(w*2),f=Math.round((kcal*.25)/9),carb=Math.max(0,Math.round((kcal-p*4-f*9)/4));return {bmr:Math.round(bmr),kcal,p,carb,f}}
const save=()=>localStorage.setItem(KEY,JSON.stringify(D));
const C=()=>D.clients.find(c=>c.id===S.cid)||D.clients[0];
const P=()=>D.programs.find(p=>p.id===C().programId);
const F=()=>D.diets.find(f=>f.id===C().dietId);
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const nav=[["home","⌂","Koti"],["clients","♙","Asiakkaat"],["workouts","▣","Harjoitukset"],["food","◒","Ravinto"],["messages","✉","Viestit"]];

function render(){app.innerHTML=`<div class="app"><div class="top"><div class="logo">BUILT<i>.</i></div></div><div class="role-switch"><button class="${S.role==="coach"?"on":""}" data-role="coach">Valmentaja</button><button class="${S.role==="client"?"on":""}" data-role="client">Asiakas</button></div>${view()}<div class="bottom">${nav.map(n=>`<button class="${S.page===n[0]?"on":""}" data-nav="${n[0]}"><b>${n[1]}</b>${n[2]}</button>`).join("")}</div></div>`;document.querySelectorAll("[data-nav]").forEach(x=>x.onclick=()=>{S.page=x.dataset.nav;render()});document.querySelectorAll("[data-role]").forEach(x=>x.onclick=()=>{S.role=x.dataset.role;S.page=S.role==="coach"?"home":"clienthome";render()});bind()}
function clientPicker(){return `<div class="clients">${D.clients.map(c=>`<button class="client ${c.id===S.cid?"on":""}" data-client="${c.id}">${esc(c.name)}</button>`).join("")}</div>`}
function home(){let c=C(),p=P(),f=F();return `<h1>Hei ${esc(c.name)}</h1>${clientPicker()}<div class="grid"><div class="card"><div class="muted">Paino</div><h2>${c.weight} kg</h2></div><div class="card"><div class="muted">Tavoite</div><h2>${c.goal} kg</h2></div></div><div class="card"><h3>Edistyminen</h3><div class="muted">${c.history.join(" → ")} kg</div><button class="btn soft wide" data-page="clients">Painon seuranta</button></div><div class="card"><h3>Seuraava harjoitus</h3><div class="muted">${esc(p?.name||"Ei ohjelmaa")}</div><button class="btn primary wide" data-page="workouts">Avaa harjoitukset</button></div><div class="card"><h3>Ravinto</h3><div class="muted">${esc(f?.name||"Ei ruokavaliota")}</div><button class="btn primary wide" data-page="food">Avaa ravinto</button></div></div>`}
function clients(){return `<h1>Asiakkaat</h1>${clientPicker()}${D.clients.map(c=>`<div class="card"><div class="row"><div><h3>${esc(c.name)}</h3><div class="muted">${c.weight} kg → ${c.goal} kg</div></div><button class="btn" data-open="${c.id}">Avaa</button></div><div class="field"><label>Lisää paino</label><div class="row"><input style="flex:1;padding:10px;border:1px solid #ddd;border-radius:10px" data-weight="${c.id}" type="number" step=".1" value="${c.weight}"><button class="btn soft" data-saveweight="${c.id}">Tallenna</button></div></div></div>`).join("")}<button class="btn primary wide" id="addClient">+ Lisää asiakas</button>`}
function workouts(){return `<h1>Harjoitukset</h1>${clientPicker()}<div class="card"><h3>${esc(C().name)}</h3><div class="muted">Asiakkaan ohjelma: ${esc(P()?.name||"ei asetettu")}</div></div><button class="btn primary wide" id="createProgram">+ Luo harjoitusohjelma</button><h3 style="margin-top:20px">Valmentajan treenipankki</h3>${D.library.map(x=>`<div class="card"><div class="row"><div><h3>${esc(x.name)}</h3><div class="muted">${x.exercises.length} liikettä</div></div><button class="btn primary" data-libraryuse="${x.id}">Asiakkaalle</button></div><button class="btn soft wide" data-libraryedit="${x.id}">Muokkaa</button></div>`).join("")||`<div class="card muted">Tallenna kokonainen harjoitus tänne, kun olet rakentanut sen.</div>`}<h3 style="margin-top:20px">Ohjelmat</h3>${D.programs.map(p=>`<div class="card"><div class="row"><div><h3>${esc(p.name)}</h3><div class="muted">${esc(p.goal)} · ${p.weeks.length} viikkoa</div></div><button class="btn" data-editprogram="${p.id}">Muokkaa</button></div><button class="btn soft wide" data-assign="${p.id}">Aseta asiakkaalle</button></div>`).join("")||`<div class="card muted">Ei ohjelmia.</div>`}`}
function food(){let f=F();return `<h1>Ravinto</h1>${clientPicker()}<div class="card"><h3>${esc(f?.name||"Ei ruokavaliota")}</h3>${!f&&C().macro?`<div class="macro"><span>${C().macro.kcal} kcal</span><span>P ${C().macro.p} g</span><span>H ${C().macro.c} g</span><span>R ${C().macro.f} g</span></div><div class="muted">Asiakkaalle laskettu aloitussuositus.</div>`:""}${f?`<div class="macro"><span>${f.kcal} kcal</span><span>P ${f.p} g</span><span>H ${f.c} g</span><span>R ${f.f} g</span></div>`:`<div class="muted">Luo asiakkaalle ruokavalio alusta asti.</div>`}<button class="btn primary wide" id="createDiet">${f?"Muokkaa ruokavaliota":"+ Luo ruokavalio"}</button></div><div class="card"><h3>Ruokapankki</h3><div class="muted">Valmiit ja itse luodut ateriat.</div><button class="btn soft wide" data-page="foodbank">Avaa ruokapankki</button></div>${(f?.meals||[]).map(id=>{let m=D.meals.find(x=>x.id===id);return m?mealCard(m,false):""}).join("")}`}
function mealCard(m,add=true){return `<div class="meal"><div class="row"><div><h3>${esc(m.name)}</h3><div class="macro"><span>${m.kcal} kcal</span><span>P ${m.p}</span><span>H ${m.c}</span><span>R ${m.f}</span></div><div class="muted">${esc(m.foods)}</div></div>${add?`<button class="btn primary" data-addmeal="${m.id}">+ Lisää</button>`:""}</div></div>`}
function foodbank(){let f=F(),t=f||{p:180,c:250,f:70};let score=m=>Math.abs(m.p-t.p*.2)+Math.abs(m.c-t.c*.2)+Math.abs(m.f-t.f*.2);return `<h1>Ruokapankki</h1>${clientPicker()}<div class="card"><h3>Makroihin sopivat ateriat</h3><div class="muted">Asiakkaan tavoite: P ${t.p} · H ${t.c} · R ${t.f}</div></div>${["Aamiainen","Lounas","Päivällinen","Välipala"].map(cat=>`<h3>${cat}</h3>${D.meals.filter(m=>m.cat===cat).sort((a,b)=>score(a)-score(b)).map(m=>mealCard(m,true)).join("")}`).join("")}<button class="btn soft wide" id="newMeal">+ Luo oma ateria</button>`}
function messages(){return `<h1>Viestit</h1>${clientPicker()}<div class="card"><h3>${esc(C().name)}</h3><textarea id="msg" style="width:100%;min-height:100px;border:1px solid #ddd;border-radius:10px;padding:10px" placeholder="Kirjoita viesti asiakkaalle…"></textarea><button class="btn primary wide" id="send">Lähetä</button></div>`}

function programEditor(p){return `<div class="modal"><div class="sheet"><div class="row"><h2>Rakenna harjoitus</h2><button class="btn danger" id="closeEditor">Sulje</button></div><div class="field"><label>Harjoituksen nimi</label><input id="progName" value="${esc(p.name)}"></div><div class="field"><label>Tavoite</label><select id="progGoal">${["Voima","Hypertrofia","Olympianostot","Yleiskunto"].map(x=>`<option ${p.goal===x?"selected":""}>${x}</option>`).join("")}</select></div>${p.weeks.map((w,wi)=>`<div class="week"><div class="row"><h3>${esc(w.name)}</h3><button class="btn danger" data-delweek="${wi}">×</button></div>${w.days.map((d,di)=>`<div class="day"><div class="field"><label>Treeni</label><input data-dayname="${wi}:${di}" value="${esc(d.name)}"></div>${d.exercises.map((x,xi)=>`<div class="exercise"><div class="exgrid"><input data-ex="${wi}:${di}:${xi}:0" value="${esc(x.name)}" placeholder="Liike"><input data-ex="${wi}:${di}:${xi}:1" type="number" value="${x.sets}" placeholder="Sarjat"><input data-ex="${wi}:${di}:${xi}:2" value="${esc(x.reps)}" placeholder="Toistot"><input data-ex="${wi}:${di}:${xi}:3" value="${esc(x.rest)}" placeholder="Palautus"><button class="btn danger" data-delex="${wi}:${di}:${xi}">×</button></div></div>`).join("")}<button class="btn soft" data-addex="${wi}:${di}">+ Liike</button><button class="btn danger wide" data-deld="${wi}:${di}">Poista treenipäivä</button></div>`).join("")}<button class="btn soft" data-addday="${wi}">+ Treenipäivä</button></div>`).join("")}<button class="btn soft wide" id="addWeek">+ Viikko</button><div class="editor-actions"><button class="btn primary wide" id="saveProgram">Tallenna ohjelma</button><button class="btn primary wide" id="saveLibrary">Tallenna myös treenipankkiin</button></div></div></div>`}
function dietEditor(f){return `<div class="modal"><div class="sheet"><h2>Rakenna ruokavalio</h2><div class="field"><label>Nimi</label><input id="dietName" value="${esc(f.name)}"></div><div class="grid"><div class="field"><label>kcal</label><input id="dk" type="number" value="${f.kcal}"></div><div class="field"><label>Proteiini g</label><input id="dp" type="number" value="${f.p}"></div><div class="field"><label>Hiilihydraatit g</label><input id="dc" type="number" value="${f.c}"></div><div class="field"><label>Rasva g</label><input id="df" type="number" value="${f.f}"></div></div><h3>Ateriat</h3>${(f.meals||[]).map(id=>{let m=D.meals.find(x=>x.id===id);return m?`<div class="meal row"><b>${esc(m.name)}</b><button class="btn danger" data-rm="${id}">Poista</button></div>`:""}).join("")}<button class="btn soft wide" id="toFoodBank">+ Lisää ateria ruokapankista</button><button class="btn primary wide" id="saveDiet">Tallenna ruokavalio</button><button class="btn soft wide" id="closeDiet">Sulje</button></div></div>`}

function clienthome(){let c=C(),p=P(),f=F();return `<h1>Hei ${esc(c.name)}</h1><div class="card"><div class="muted">Paino</div><h2>${c.weight} kg</h2><div class="muted">Tavoite ${c.goal} kg</div></div><div class="card"><h3>Oma harjoitusohjelma</h3><div class="muted">${esc(p?.name||"Valmentaja ei ole vielä lisännyt ohjelmaa.")}</div>${p?`<button class="btn primary wide" data-page="clientworkout">Avaa ohjelma</button>`:""}</div><div class="card"><h3>Oma ravinto</h3><div class="muted">${esc(f?.name||"Valmentaja ei ole vielä lisännyt ruokavaliota.")}</div>${f?`<button class="btn primary wide" data-page="clientfood">Avaa ruokavalio</button>`:""}</div>`}
function clientworkout(){let p=P();return `<h1>Harjoitusohjelma</h1>${p?`${p.weeks.map(w=>`<div class="week"><h3>${esc(w.name)}</h3>${w.days.map(d=>`<div class="day"><h3>${esc(d.name)}</h3>${d.exercises.map(x=>`<div class="exercise"><div class="row"><b>${esc(x.name)}</b><span class="muted">${x.sets} × ${esc(x.reps)}</span></div><div class="muted">Palautus ${esc(x.rest)}</div></div>`).join("")}</div>`).join("")}</div>`).join("")}`:`<div class="card muted">Ei ohjelmaa.</div>`}`}
function clientfood(){let f=F();return `<h1>Ruokavalio</h1>${f?`<div class="card"><h3>${esc(f.name)}</h3><div class="macro"><span>${f.kcal} kcal</span><span>P ${f.p} g</span><span>H ${f.c} g</span><span>R ${f.f} g</span></div></div>${(f.meals||[]).map(id=>{let m=D.meals.find(x=>x.id===id);return m?mealCard(m,false):""}).join("")}`:`<div class="card muted">Ei ruokavaliota.</div>`}`}

function view(){if(S.role==="client")return ({clienthome,clientworkout,clientfood}[S.page]||clienthome)();return ({home,clients,workouts,food,foodbank,messages}[S.page]||home)()}

function bind(){
document.querySelectorAll("[data-client]").forEach(b=>b.onclick=()=>{S.cid=+b.dataset.client;render()});
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{S.page=b.dataset.page;render()});
document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>{S.cid=+b.dataset.open;S.page="home";render()});
let a=document.getElementById("addClient");if(a)a.onclick=()=>openClientForm();\ndocument.querySelectorAll("[data-saveweight]").forEach(b=>b.onclick=()=>{let c=D.clients.find(x=>x.id===+b.dataset.saveweight),i=document.querySelector(`[data-weight="${b.dataset.saveweight}"]`);c.weight=+i.value;c.history.push(c.weight);save();render()});
let cp=document.getElementById("createProgram");if(cp)cp.onclick=()=>openProgram({id:Date.now(),name:"Uusi harjoitus",goal:"Voima",weeks:[{name:"Viikko 1",days:[{name:"Treeni A",exercises:[]}]}]});
document.querySelectorAll("[data-editprogram]").forEach(b=>b.onclick=()=>openProgram(D.programs.find(p=>p.id===+b.dataset.editprogram)));
document.querySelectorAll("[data-assign]").forEach(b=>b.onclick=()=>{C().programId=+b.dataset.assign;save();render()});
document.querySelectorAll("[data-libraryuse]").forEach(b=>{b.onclick=()=>{let l=D.library.find(x=>x.id===+b.dataset.libraryuse);let p={id:Date.now(),name:l.name,goal:l.goal,weeks:[{name:"Viikko 1",days:[{name:"Treeni",exercises:JSON.parse(JSON.stringify(l.exercises))}]}]};D.programs.push(p);C().programId=p.id;save();render()}});
document.querySelectorAll("[data-libraryedit]").forEach(b=>b.onclick=()=>{let l=D.library.find(x=>x.id===+b.dataset.libraryedit);openProgram({id:Date.now(),name:l.name,goal:l.goal,weeks:[{name:"Viikko 1",days:[{name:"Treeni",exercises:JSON.parse(JSON.stringify(l.exercises))}]}]},l.id)});
let cd=document.getElementById("createDiet");if(cd)cd.onclick=()=>openDiet(F()||{id:Date.now(),name:"Uusi ruokavalio",kcal:2500,p:180,c:250,f:70,meals:[]});
document.querySelectorAll("[data-addmeal]").forEach(b=>b.onclick=()=>{let f=F();if(!f){alert("Luo ensin ruokavalio.");return}f.meals=f.meals||[];if(!f.meals.includes(+b.dataset.addmeal))f.meals.push(+b.dataset.addmeal);save();render()});
let nm=document.getElementById("newMeal");if(nm)nm.onclick=()=>{let name=prompt("Aterian nimi");if(!name)return;D.meals.push({id:Date.now(),name,cat:prompt("Kategoria","Välipala")||"Välipala",kcal:+(prompt("kcal","400")||400),p:+(prompt("Proteiini g","30")||30),c:+(prompt("Hiilihydraatit g","40")||40),f:+(prompt("Rasva g","10")||10),foods:prompt("Ruoka-aineet","")||""});save();render()};
let send=document.getElementById("send");if(send)send.onclick=()=>{alert("Viestin testilähetys valmis.");document.getElementById("msg").value=""}
}


function openClientForm(){
document.body.insertAdjacentHTML("beforeend",`<div class="modal"><div class="sheet"><h2>Uusi asiakas</h2>
<div class="field"><label>Nimi</label><input id="cn" placeholder="Asiakkaan nimi"></div>
<div class="grid"><div class="field"><label>Paino kg</label><input id="cw" type="number" value="80"></div><div class="field"><label>Pituus cm</label><input id="ch" type="number" value="177"></div><div class="field"><label>Ikä</label><input id="ca" type="number" value="30"></div><div class="field"><label>Tavoite</label><select id="cg"><option value="maintain">Painon ylläpito</option><option value="lose">Painonpudotus</option><option value="gain">Lihasmassan / painon nosto</option></select></div></div>
<div class="field"><label>Aktiivisuus</label><select id="cact"><option value="low">Kevyt</option><option value="moderate" selected>Kohtalainen</option><option value="high">Aktiivinen</option><option value="veryhigh">Erittäin aktiivinen</option></select></div>
<div class="card" id="macroPreview"><h3>Suositus</h3><div class="muted">Täytä tiedot, niin makrot lasketaan.</div></div>
<div class="editor-actions"><button class="btn primary wide" id="createClient">Luo asiakas</button><button class="btn soft wide" id="cancelClient">Peruuta</button></div>
</div></div>`);
let m=document.querySelector(".modal:last-child");
let update=()=>{let temp={weight:+m.querySelector("#cw").value,height:+m.querySelector("#ch").value,age:+m.querySelector("#ca").value,goal:m.querySelector("#cg").value,activity:m.querySelector("#cact").value},x=macroSuggestion(temp);m.querySelector("#macroPreview").innerHTML=`<h3>Suositeltu aloitus</h3><div class="macro"><span>${x.kcal} kcal</span><span>P ${x.p} g</span><span>H ${x.carb} g</span><span>R ${x.f} g</span></div><div class="muted">BMR noin ${x.bmr} kcal. Voit muokata makroja myöhemmin ruokavaliossa.</div>`};
["cw","ch","ca","cg","cact"].forEach(id=>m.querySelector("#"+id).oninput=update);update();
m.querySelector("#cancelClient").onclick=()=>m.remove();
m.querySelector("#createClient").onclick=()=>{let n=m.querySelector("#cn").value.trim();if(!n){alert("Anna asiakkaalle nimi.");return}let temp={weight:+m.querySelector("#cw").value,height:+m.querySelector("#ch").value,age:+m.querySelector("#ca").value,goal:m.querySelector("#cg").value,activity:m.querySelector("#cact").value};let x=macroSuggestion(temp);let c={id:Date.now(),name:n,weight:temp.weight,height:temp.height,age:temp.age,goal:temp.goal,activity:temp.activity,history:[temp.weight],programId:null,dietId:null,macro:{kcal:x.kcal,p:x.p,c:x.carb,f:x.f}};D.clients.push(c);S.cid=c.id;save();m.remove();render()};
}

function openProgram(p,libraryId=null){if(!p)return;document.body.insertAdjacentHTML("beforeend",programEditor(p));let m=document.querySelector(".modal:last-child");
m.querySelector("#closeEditor").onclick=()=>m.remove();
m.querySelector("#addWeek").onclick=()=>{p.weeks.push({name:"Viikko "+(p.weeks.length+1),days:[]});m.remove();openProgram(p,libraryId)};
m.querySelectorAll("[data-addday]").forEach(b=>b.onclick=()=>{p.weeks[+b.dataset.addday].days.push({name:"Uusi treeni",exercises:[]});m.remove();openProgram(p,libraryId)});
m.querySelectorAll("[data-addex]").forEach(b=>b.onclick=()=>{let[w,d]=b.dataset.addex.split(":").map(Number);p.weeks[w].days[d].exercises.push({name:"Uusi liike",sets:3,reps:"8-12",rest:"90 s"});m.remove();openProgram(p,libraryId)});
m.querySelectorAll("[data-delex]").forEach(b=>b.onclick=()=>{let[w,d,x]=b.dataset.delex.split(":").map(Number);p.weeks[w].days[d].exercises.splice(x,1);m.remove();openProgram(p,libraryId)});
m.querySelectorAll("[data-deld]").forEach(b=>b.onclick=()=>{let[w,d]=b.dataset.deld.split(":").map(Number);p.weeks[w].days.splice(d,1);m.remove();openProgram(p,libraryId)});
m.querySelectorAll("[data-delweek]").forEach(b=>b.onclick=()=>{if(p.weeks.length>1)p.weeks.splice(+b.dataset.delweek,1);m.remove();openProgram(p,libraryId)});
m.querySelectorAll("[data-dayname]").forEach(i=>i.onchange=()=>{let[w,d]=i.dataset.dayname.split(":").map(Number);p.weeks[w].days[d].name=i.value});
m.querySelectorAll("[data-ex]").forEach(i=>i.onchange=()=>{let[w,d,x,k]=i.dataset.ex.split(":").map(Number),v=i.value;let a=p.weeks[w].days[d].exercises[x];if(k===0)a.name=v;if(k===1)a.sets=+v;if(k===2)a.reps=v;if(k===3)a.rest=v});
m.querySelector("#saveProgram").onclick=()=>{p.name=m.querySelector("#progName").value||"Harjoitus";p.goal=m.querySelector("#progGoal").value;let old=D.programs.findIndex(x=>x.id===p.id);if(old<0)D.programs.push(p);C().programId=p.id;save();m.remove();render()};
m.querySelector("#saveLibrary").onclick=()=>{p.name=m.querySelector("#progName").value||"Harjoitus";p.goal=m.querySelector("#progGoal").value;let ex=p.weeks.flatMap(w=>w.days.flatMap(d=>d.exercises));let lib={id:libraryId||Date.now(),name:p.name,goal:p.goal,exercises:JSON.parse(JSON.stringify(ex))};let ix=D.library.findIndex(x=>x.id===lib.id);if(ix>=0)D.library[ix]=lib;else D.library.push(lib);save();m.remove();render()}
}
function openDiet(f){document.body.insertAdjacentHTML("beforeend",dietEditor(f));let m=document.querySelector(".modal:last-child");
m.querySelector("#closeDiet").onclick=()=>m.remove();
m.querySelector("#toFoodBank").onclick=()=>{m.remove();S.page="foodbank";render()};
m.querySelectorAll("[data-rm]").forEach(b=>b.onclick=()=>{f.meals=f.meals.filter(x=>x!==+b.dataset.rm);m.remove();openDiet(f)});
m.querySelector("#saveDiet").onclick=()=>{f.name=m.querySelector("#dietName").value||"Ruokavalio";f.kcal=+m.querySelector("#dk").value||0;f.p=+m.querySelector("#dp").value||0;f.c=+m.querySelector("#dc").value||0;f.f=+m.querySelector("#df").value||0;let ix=D.diets.findIndex(x=>x.id===f.id);if(ix<0)D.diets.push(f);C().dietId=f.id;save();m.remove();render()}
}
render();
