/* FitApp V1.3 patch */
D.clients.forEach(c=>{c.dailyWorkout=c.dailyWorkout||{};c.dailyMeal=c.dailyMeal||{};c.weightDates=c.weightDates||[];c.openWeeks=c.openWeeks||{}});
function dayKey(){return new Date().toISOString().slice(0,10)}
function dateLabel(k){return new Date(k+'T12:00:00').toLocaleDateString('fi-FI',{weekday:'short',day:'numeric',month:'numeric',year:'numeric'})}
function clientHome(){const c=client(),p=program(),done=Object.keys(c.dailyWorkout||{}).filter(k=>c.dailyWorkout[k]).length;return `<h1>Oma päivä</h1><div class="card"><h3>${esc(c.name)}</h3><div class="muted">Paino ${c.weight} kg</div></div><div class="grid"><div class="card"><div class="muted">Tehdyt harjoitukset</div><h2>${done}</h2><button class="btn primary wide" data-nav="clientworkout">Avaa harjoitukset</button></div><div class="card"><div class="muted">Ruokavalio</div><button class="btn primary wide" data-nav="clientfood">Avaa ruokavalio</button></div></div><div class="card"><h3>Valmentajan ohjelma</h3><div class="muted">${esc(p?.name||'Ei vielä ohjelmaa')}</div></div>`}
function clientWorkout(){const c=client(),p=program(),today=dayKey();if(!p)return '<h1>Harjoitukset</h1><div class="card muted">Ei ohjelmaa.</div>';return `<h1>Harjoitukset</h1>${p.weeks.map((w,wi)=>`<div class="week"><button class="weekToggle" data-client-week="${wi}"><b>${esc(w.name||('Viikko '+(wi+1)))}</b><span>${c.openWeeks[wi]===false?'+':'−'}</span></button>${c.openWeeks[wi]===false?'':w.days.map((d,di)=>{const k=today+'|'+wi+'|'+di;return `<div class="day"><div class="row"><h3>${esc(d.name||('Päivä '+(di+1)))}</h3>${statusPill(!!c.dailyWorkout[k])}</div>${d.sections.map(s=>`<div class="section"><h3>${esc(s.name)}</h3>${s.exercises.map(x=>`<div class="exercise"><b>${esc(x.name)}</b><div class="muted">${x.sets} × ${esc(x.reps)} · ${esc(x.rest)}</div>${x.info?`<div class="note">${esc(x.info)}</div>`:''}</div>`).join('')}</div>`).join('')}<button class="btn ${c.dailyWorkout[k]?'success':'primary'} wide" data-day-workout="${k}">${c.dailyWorkout[k]?'Merkitse tekemättömäksi':'Kuittaa harjoitus tehdyksi'}</button></div>`}).join('')}</div>`).join('')}`}
function clientFood(){const c=client(),f=diet(),today=dayKey();if(!f)return '<h1>Ruokavalio</h1><div class="card muted">Ei ruokavaliota.</div>';const eaten=(f.meals||[]).filter(id=>c.dailyMeal[today+'|'+id]).reduce((a,id)=>a+(D.meals.find(x=>x.id===id)?.kcal||0),0);return `<h1>Ruokavalio</h1><div class="card"><div class="grid"><div class="stat"><div class="muted">Tavoite päivässä</div><b>${f.kcal} kcal</b></div><div class="stat"><div class="muted">Syöty tänään</div><b>${eaten} kcal</b></div></div></div>${(f.meals||[]).map(id=>{let m=D.meals.find(x=>x.id===id),done=!!c.dailyMeal[today+'|'+id];return m?`<div class="meal"><div class="row"><div><h3>${esc(m.name)}</h3><div class="muted">${m.kcal} kcal · P ${m.p} · H ${m.c} · R ${m.f}</div></div>${statusPill(done)}</div><button class="btn ${done?'success':'primary'} wide" data-day-meal="${id}">${done?'Merkitse syömättömäksi':'Kuittaa syödyksi'}</button><button class="btn soft wide" data-alt-meal="${id}">Ilmoita vaihtoehtoinen ruoka</button></div>`:''}).join('')}`}
function progressChart(c){const a=c.history||[];if(!a.length)return '<div class="muted">Ei vielä painomittauksia.</div>';const min=Math.min(...a)-1,max=Math.max(...a)+1,W=340,H=190,p=28,pts=a.map((v,i)=>{const x=p+(a.length===1?0:i*(W-2*p)/(a.length-1)),y=H-p-(v-min)/(max-min)*(H-2*p);return[x,y]});return `<div class="chart"><svg viewBox="0 0 ${W} ${H}"><polyline points="${pts.map(x=>x.join(',')).join(' ')}" fill="none" stroke="#6f46d8" stroke-width="3"/>${a.map((v,i)=>`<circle cx="${pts[i][0]}" cy="${pts[i][1]}" r="4" fill="#6f46d8"/><text x="${pts[i][0]}" y="${pts[i][1]-9}" text-anchor="middle" font-size="11">${v} kg</text>`).join('')}</svg></div>`}
function coachStatus(){const c=client(),p=program(),f=diet(),days=(p?.weeks||[]).flatMap((w,wi)=>w.days.map((d,di)=>({wi,di,d}))),dates=[...new Set(Object.keys(c.dailyWorkout||{}).map(k=>k.split('|')[0]).concat(Object.keys(c.dailyMeal||{}).map(k=>k.split('|')[0])))].sort().reverse();return `<div class="card"><h3>Asiakkaan ilmoittama toteuma</h3>${dates.length?dates.map(date=>{const wd=days.filter(x=>c.dailyWorkout[date+'|'+x.wi+'|'+x.di]);const meals=(f?.meals||[]).filter(id=>c.dailyMeal[date+'|'+id]);return `<div class="stat" style="margin-top:8px"><b>${dateLabel(date)}</b><div>Harjoitukset: ${wd.length?wd.map(x=>esc(x.d.name)).join(', '):'ei kuitattuja'}</div><div>Ruuat: ${meals.length?meals.map(id=>esc(D.meals.find(m=>m.id===id)?.name||'Ateria')).join(', '):'ei kuitattuja'}</div></div>`}).join(''):'<div class="muted">Ei vielä päiväkohtaisia kuittauksia.</div>'}</div>`}
// Upgrade workout editor rendering with exercise info and reliable section persistence.
const _weekHtml=weekHtml;
weekHtml=function(w,wi){let h=_weekHtml(w,wi);return h.replace(/(<div class="exercise">)(<div class="exgrid">)/g,'$1$2').replace(/(<\/div><\/div>)(<\/div>`)/g,'$1$2')}
// Save editor state before structural changes; patch existing bindEditor.
const _bindEditor=bindEditor;
bindEditor=function(m,p,refresh){m.querySelectorAll('[data-week],[data-day],[data-section],[data-ex]').forEach(el=>el.addEventListener('input',()=>readProgram(m,p)));m.querySelectorAll('[data-addsection],[data-addday],[data-addex],[data-delex],[data-delsection],[data-deld],[data-delweek]').forEach(b=>b.addEventListener('click',()=>readProgram(m,p),{capture:true}));_bindEditor(m,p,refresh)}
// Daily handlers.
function v13bind(){document.querySelectorAll('[data-day-workout]').forEach(b=>b.onclick=()=>{const k=b.dataset.dayWorkout;if(client().dailyWorkout[k])delete client().dailyWorkout[k];else client().dailyWorkout[k]=Date.now();save();render()});document.querySelectorAll('[data-day-meal]').forEach(b=>b.onclick=()=>{const k=dayKey()+'|'+b.dataset.dayMeal;if(client().dailyMeal[k])delete client().dailyMeal[k];else client().dailyMeal[k]=Date.now();save();render()});document.querySelectorAll('[data-client-week]').forEach(b=>b.onclick=()=>{const i=+b.dataset.clientWeek;client().openWeeks[i]=client().openWeeks[i]===false;save();render()});document.querySelectorAll('[data-saveweight]').forEach(b=>{b.addEventListener('click',()=>{if(b.dataset.v13done)return;b.dataset.v13done='1';const c=D.clients.find(x=>x.id===+b.dataset.saveweight);const i=document.querySelector(`[data-weight="${b.dataset.saveweight}"]`),v=+i.value,today=dayKey();if(c.weightDates.includes(today)){alert('Tämän päivän paino on jo tallennettu.');return}c.weight=v;c.history.push(v);c.weightDates.push(today);save();alert('Uusi paino tallennettu.');render()},{capture:true})})}
const _render=render;render=function(){_render();v13bind()}
